export const POSTS_GET_REQUEST = 'POSTS_GET_REQUEST'
export const POSTS_GET_SUCCESS = 'POSTS_GET_SUCCESS'
export const POSTS_GET_ERROR = 'POSTS_GET_ERROR'

export const NEW_POST_REQUEST = 'NEW_POST_REQUEST'
export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_ERROR = 'NEW_POST_ERROR'
export const NEW_POST_CLEAR = 'NEW_POST_CLEAR'

export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST'
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS'
export const POST_DETAIL_ERROR = 'POST_DETAIL_ERROR'
export const POST_DETAIL_CLEAR = 'POST_DETAIL_CLEAR'

export const POST_UPDATE_LIKES_REQUEST = 'POST_UPDATE_LIKES_REQUEST'
export const POST_UPDATE_LIKES_SUCCESS = 'POST_UPDATE_LIKES_SUCCESS'
export const POST_UPDATE_LIKES_ERROR = 'POST_UPDATE_LIKES_ERROR'

export const POST_CREATE_COMMENT_REQUEST = 'POST_CREATE_COMMENT_REQUEST'
export const POST_CREATE_COMMENT_SUCCESS = 'POST_CREATE_COMMENT_SUCCESS'
export const POST_CREATE_COMMENT_ERROR = 'POST_CREATE_COMMENT_ERROR'

export const POST_DELETE_COMMENT_REQUEST = 'POST_DELETE_COMMENT_REQUEST'
export const POST_DELETE_COMMENT_SUCCESS = 'POST_DELETE_COMMENT_SUCCESS'
export const POST_DELETE_COMMENT_ERROR = 'POST_DELETE_COMMENT_ERROR'
export const POST_DELETE_COMMENT_CLEAR = 'POST_DELETE_COMMENT_CLEAR'

